import type { MemoRenderInput } from "./memo.schema";

export const AcmeMemoRenderInput: MemoRenderInput = {
  maxPages: null,
  generatedAt: 1_777_680_000_000,
  company: {
    id: "acme-robotics",
    name: "Acme Robotics",
    stage: "Seed",
    sector: "Robotics",
    location: "Pittsburgh, PA",
    description: "Warehouse autonomy for mid-market 3PLs.",
    website: "https://acme-robotics.com",
    score: 60,
    recommendation: "watch",
  },
  summary: {
    headline: "Acme has credible early traction, but financial evidence conflicts.",
    thesis:
      "The company shows real customer pull and robotics-market relevance, but the current source set leaves GTM depth, durability of growth, and competitive positioning under-verified.",
    executiveSummary: null,
    keyTakeaways: [
      "Pitch deck claims $1.2M ARR and 22% MoM growth.",
      "Q3 financials show a lower ARR base after excluding pilots.",
      "Team checks are stronger than market and traction checks.",
      "The memo should not treat growth quality as resolved until revenue composition is reconciled.",
    ],
    upside: [
      "Strong technical founding profile.",
      "Large warehouse automation wedge.",
      "Attractive gross margin claim if source reconciles.",
    ],
    risks: [
      "Conflicting ARR and growth evidence.",
      "No GTM lead surfaced.",
      "Competitive landscape unresolved.",
    ],
  },
  checkGroups: [
    {
      id: "team",
      label: "Team",
      verdict: "strong",
      score: 87,
      summary: "Technical founder-market fit is the strongest part of the current diligence file.",
      checks: [
        {
          id: "team-founder-prestige",
          groupId: "team",
          label: "Founder prestige",
          status: "pass",
          score: 92,
          detail: "ex-Stripe robotics lead",
          rationale: "The founding profile is credible for a warehouse autonomy company.",
          citations: [{ sourceId: "crunchbase-acme", label: "Crunchbase profile", locator: null }],
        },
        {
          id: "team-completeness",
          groupId: "team",
          label: "Team completeness",
          status: "concern",
          score: 62,
          detail: "No GTM lead surfaced",
          rationale: "The technical bench is clear, but commercial leadership is not evidenced.",
          citations: [{ sourceId: "pitch-deck-v3", label: "Pitch deck v3", locator: "P3" }],
        },
      ],
    },
    {
      id: "market",
      label: "Market",
      verdict: "mixed",
      score: 73,
      summary: "Warehouse automation is a large wedge, but the competitive map is still thin.",
      checks: [
        {
          id: "market-tam",
          groupId: "market",
          label: "TAM credibility",
          status: "pass",
          score: 78,
          detail: "$8B automation wedge claimed",
          rationale:
            "The pitch frames a large and timely market with clear pain around warehouse labor.",
          citations: [{ sourceId: "pitch-deck-v3", label: "Pitch deck v3", locator: "P5" }],
        },
        {
          id: "market-competition",
          groupId: "market",
          label: "Competition",
          status: "unknown",
          score: 40,
          detail: null,
          rationale:
            "The available sources do not benchmark Acme against incumbents or robotics startups.",
          citations: [],
        },
      ],
    },
    {
      id: "traction",
      label: "Traction",
      verdict: "mixed",
      score: 60,
      summary: "Customer pull is visible, but ARR and growth quality conflict across sources.",
      checks: [
        {
          id: "traction-arr",
          groupId: "traction",
          label: "ARR",
          status: "concern",
          score: 58,
          detail: "$1.2M claimed vs $700k adjusted",
          rationale: "Management ARR appears to include pilots that Q3 financials exclude.",
          citations: [
            { sourceId: "pitch-deck-v3", label: "Pitch deck v3", locator: "P7" },
            { sourceId: "q3-financials", label: "Q3 financials", locator: "Sheet 1" },
          ],
        },
        {
          id: "traction-growth-rate",
          groupId: "traction",
          label: "Growth rate",
          status: "concern",
          score: 56,
          detail: "22% MoM claimed vs 11% adjusted",
          rationale: "Growth remains investable only if the recurring base reconciles cleanly.",
          citations: [
            { sourceId: "pitch-deck-v3", label: "Pitch deck v3", locator: "P7" },
            { sourceId: "q3-financials", label: "Q3 financials", locator: "Sheet 1" },
          ],
        },
      ],
    },
    {
      id: "product",
      label: "Product",
      verdict: "mixed",
      score: 68,
      summary: "The product positioning is crisp, but deployment proof is not yet deep.",
      checks: [
        {
          id: "product-positioning",
          groupId: "product",
          label: "Positioning",
          status: "pass",
          score: 74,
          detail: "Mid-market 3PL autonomy",
          rationale:
            "The website describes a focused warehouse workflow rather than broad robotics claims.",
          citations: [
            { sourceId: "acme-robotics-com", label: "Company website", locator: "Homepage" },
          ],
        },
        {
          id: "product-deployment-depth",
          groupId: "product",
          label: "Deployment depth",
          status: "unknown",
          score: 35,
          detail: null,
          rationale: "No source yet validates live production deployments or expansion behavior.",
          citations: [],
        },
      ],
    },
    {
      id: "deal-risk",
      label: "Deal Risk",
      verdict: "unknown",
      score: null,
      summary: "Pricing, round dynamics, and ownership targets are not in the current source set.",
      checks: [
        {
          id: "deal-risk-round",
          groupId: "deal-risk",
          label: "Round dynamics",
          status: "unknown",
          score: 0,
          detail: null,
          rationale: "The memo cannot assess deal risk without terms or syndicate context.",
          citations: [],
        },
      ],
    },
  ],
  sources: [
    {
      id: "pitch-deck-v3",
      kind: "pdf",
      title: "Pitch deck v3",
      subtitle: "14 pages",
      confidence: 92,
    },
    {
      id: "q3-financials",
      kind: "xlsx",
      title: "Q3 financials",
      subtitle: "4 sheets",
      confidence: 88,
    },
    {
      id: "crunchbase-acme",
      kind: "url",
      title: "crunchbase.com/acme",
      subtitle: "Company profile",
      confidence: 76,
    },
    {
      id: "acme-robotics-com",
      kind: "url",
      title: "acme-robotics.com",
      subtitle: "Homepage",
      confidence: 70,
    },
  ],
  insights: [
    {
      id: "pitch-deck-growth-excerpt",
      sourceId: "pitch-deck-v3",
      kind: "excerpt",
      locator: "P7",
      text: "Our last quarter we hit 22% MoM growth, with $1.2M ARR and a 71% gross margin.",
      linkedCheckIds: ["traction-arr", "traction-growth-rate"],
    },
    {
      id: "q3-financials-growth-excerpt",
      sourceId: "q3-financials",
      kind: "metric",
      locator: "Sheet 1",
      text: "Q3 close shows $700k ARR and 11% MoM growth after excluding pilots.",
      linkedCheckIds: ["traction-arr", "traction-growth-rate"],
    },
    {
      id: "website-positioning-excerpt",
      sourceId: "acme-robotics-com",
      kind: "claim",
      locator: "Homepage",
      text: "Autonomous warehouse cells for mid-market 3PLs that need faster picking without warehouse redesign.",
      linkedCheckIds: ["product-positioning"],
    },
    {
      id: "crunchbase-profile-excerpt",
      sourceId: "crunchbase-acme",
      kind: "note",
      locator: null,
      text: "Acme Robotics is listed as a Pittsburgh-based seed company building warehouse automation software and robotics systems.",
      linkedCheckIds: ["team-founder-prestige"],
    },
  ],
};
